server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: demo-api
          uri: lb://demo-api
          predicates:
            - Path=/demos/**
        - id: demo-inventory
          uri: lb://demo-inventory
          predicates:
            - Path=/inventories/**